spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: create-drop
    show-sql: true
